server:
  port: 8181

spring:
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    database: default
#  sql:
#    init:
#      mode: always

dataone:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./base-data-b;AUTO_SERVER=true;
    username: sa
    password: password
#    platform: org.hibernate.dialect.PostgreSQLDialect
#    driver-class-name: org.postgresql.Driver
#    jdbc-url: jdbc:postgresql://localhost:5432/toir
#    username: codela
#    password: 1

datatwo:
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./base-data-b;AUTO_SERVER=true;
    username: sa
    password: password
#    maximum-pool-size: 1







