# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGM5ZDEzYmYxMmNhNTI2MTAyMDViYzZiODM4NTEwMTM4MTQ0MWViMzBlMGFlZmQ4NjZmYWE2NDM4MjU5NjE4NmIzNzJiM2FkZTZjOGI1ODJhOTdhMWVkYzk3N2MwMWRhZDdiYjFhZGVhYzAwNGY2MDdhODQ5ZTU5MzY0ODUzMzE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
